### ISSUE TITLE
Dry air vs. moist air and tracer units

### ISSUE THREAD

**Issue by pbosler** [eagles-project/mam4xx#40]
**DECISION: we are using dry air mixing ratios as prognostics in mam4xx, just like mam4 and many other aerosol packages. Conversions will be done between dry and moist air quantities in EAMxx.**

# Summary

The dynamics of Eamxx are defined with respect to moist air so that, for example, the water vapor tracer `qv` is given as water content per unit of total air, e.g., density water vapor / density total air.  Many of our aerosol parameterizations are defined with respect to dry air, so we have to be alert to this inconsistency both for bug detection in the existing code and to make sure we don't introduce new bugs in Mam4xx. 

Fortunately, atmospheric scientists give us two terms that distinguish between definitions for water vapor:

1. Water vapor mixing ratio, usually given the symbol **_w_**, is defined with respect to _dry_ air as kg h2o vapor / kg dry air or density h2o vapor / density dry air.
2. Specific humidity, usually given the symbol **_q_**, is defined with respect to moist air as kg h2o vapor / kg moist air (or densities).  

For other tracers, such as aerosols mass and number concentrations/mixing ratios etc., we'll need to be careful to know whether or not they are defined with respect to dry air or moist air.

The file `conversions.hpp` contains functions that convert to and from each (moist or dry) representation for water vapor; for other tracers we'll need to write analogous methods.

[This web page](https://www.e-education.psu.edu/meteo300/node/519) matches the definitions from standard meteorology texts and shows how to convert between moist and dry water vapor content definitions.

## To-do:

- [ ] Write conversion function for mass mixing ratio defined with respect to moist air to the same mass ratio with respect to dry air
- [ ] Write the inverse conversion
- [ ] Write unit tests
